# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest

parameters:
  - name: filenames
    type: object
    default: ['dummyfile.txt','dummyfile2.txt']
  - name: getFile
    type: boolean
    default: false
    
stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - ${{ each filename in parameters.filenames }}:
      - powershell: |
         Write-Host "##vso[task.setvariable variable=myVar;]Test-Path src/releasedocs/${{ filename }}"
      - script: echo ${{ parameters.getFile }}
      condition: and(succeeded(), eq(variables.getFile, true))
  - job: A2
    dependsOn: A1
    condition: failed()    
    steps:
    - script: echo missing files
      