# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pool:
  vmImage: ubuntu-latest

parameters:
  - name: filenames
    type: object
    default: ['dummyfile.txt','dummyfile2.txt']
  - name: getFile
    type: boolean
    default: false
    
stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - ${{ each filename in parameters.filenames }}:
      - powershell: |
         Write-Host "##vso[task.setvariable variable=getFile;]Test-Path src/releasedocs/${{ filename }}"
      - script: echo ${{ parameters.getFile }}
      - script: exit 1
        # condition: ${{ eq(parameters.getFile, false) }}

- stage: B
  condition: ${{ eq(parameters.getFile, true) }}
  jobs:
  - job:
    steps:
    - script: echo "hello world"

  # - ${{ if eq(parameters.getFile, true) }}:      
  #   - job: A2
  #     steps:
  #     - script: Test-Path "vereiste bestanden zijn niet aanwezig"
  #       # condition: ${{ eq(parameters.getFile, true) }}


# stages:
# - stage: A
#   jobs:
#   - job: A1
#     steps:
#     - ${{ each filename in parameters.filenames }}:
#       - powershell: Test-Path "src/releasedocs/filename"